### ISSUE TITLE
关于M3FD数据集脚本的运行

### ISSUE THREAD

**Issue by ciderjoy** [XueZ-phd/Efficient-RGB-T-Early-Fusion-Detection#1]
作者团队你好。
直接运行`python ./m3fd2coco.py`貌似无法直接构建出需要的json文件，因为脚本中要求的M3FD的目录结构貌似与原始的M3FD的结构不一致。
原始的数据集目录结构为
```
├─M3FD_Detection
           ├─Annotation
           ├─ir
           ├─labels
           ├─vi
```

**Comment by XueZ-phd** [comment]
Hello @BeiYining ,


Thanks for your interest in our work!

To generate the COCO format dataset, you should first convert the dataset into the YOLO format. This is because we conduct experiments using both YOLOv5 and MMDetection, and we construct these two formats.

Therefore, you just need to follow the instructions provided in README.md, and you can obtain the COCO format dataset.


--------------------------------------------

![image](https://github.com/XueZ-phd/Efficient-RGB-T-Early-Fusion-Detection/assets/58646903/ac1b2c63-7a13-44ed-93fc-8fad39bc3d7e)
